name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest] # unit tests already run on Ubuntu

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install build tools
      run: python3 -m pip install --upgrade build && git submodule init && git submodule update

    - name: Set up debugging tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Build pykmn
      run: python3 -m build

    - name: Install pykmn
      run: python3 -m pip install --find-links=dist pykmn

    - name: Verify `engine` module is accessible
      if: ${{ matrix.os != 'windows-latest' }} # this doesn't work on Windows
      run: |
        echo "from pykmn.engine import rng
        print(rng.ShowdownRNG(35).next())" | python3
      # use a different working directory so that Python sees the installed wheel
      working-directory: engine
