name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # unit tests already run on Ubuntu
        # Windows builds are currently disabled due to a bug with the build
        # I *think* it's an upstream issue, but I'm not 100% sure
        os: [macos-latest] # [windows-latest, macos-latest] 
        

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install build tools
      run: python3 -m pip install --upgrade build

    - name: Set up MinGW
      if: ${{ matrix.os == 'windows-latest' }}
      uses: egor-tensin/setup-clang@v1
      with:
        platform: x64

    - name: Set up debugging tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Build PyKMN
      run: python3 -m build

    - name: Install PyKMN
      run: python3 -m pip install --find-links=dist pykmn

    - name: Verify `engine` module is accessible
      if: ${{ matrix.os != 'windows-latest' }} # this doesn't work on Windows
      run: |
        echo "from pykmn.engine import rng
        print(rng.ShowdownRNG(35).next())" | python3
      # use a different working directory so that Python sees the installed wheel
      working-directory: engine
