name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install testing tools
      run: python3 -m pip install flake8 mypy flake8-docstrings build
        coverage cffi requests
        types-cffi types-requests types-setuptools

    - name: Set up debugging tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Lint
      run: flake8 .

    - name: Check types
      run: mypy .

    - name: Build pykmn
      run: python3 -m build

    - name: Install pykmn
      run: python3 -m pip install --find-links=dist pykmn

    - name: Run unit tests
      run: python3 -m coverage run -m unittest discover tests

    - name: Generate test coverage report
      run: python3 -m coverage xml --include='pykmn/*'

    - name: Upload test coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
